<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQcFnaE2\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQcFnaE2/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerQcFnaE2.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerQcFnaE2\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerQcFnaE2\appAppKernelProdContainer([
    'container.build_hash' => 'QcFnaE2',
    'container.build_id' => '57f5ecaf',
    'container.build_time' => 1732716301,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQcFnaE2');
